# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ele_version7_7.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1360, 750)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1360, 750))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1360, 750))
        self.centralwidget.setMaximumSize(QtCore.QSize(1360, 750))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.base_frame1 = QtGui.QFrame(self.centralwidget)
        self.base_frame1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_frame1.sizePolicy().hasHeightForWidth())
        self.base_frame1.setSizePolicy(sizePolicy)
        self.base_frame1.setMinimumSize(QtCore.QSize(500, 750))
        self.base_frame1.setMaximumSize(QtCore.QSize(500, 750))
        self.base_frame1.setStyleSheet(_fromUtf8("background:#CCCCCC;"))
        self.base_frame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.base_frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.base_frame1.setObjectName(_fromUtf8("base_frame1"))
        self.frame_4 = QtGui.QFrame(self.base_frame1)
        self.frame_4.setGeometry(QtCore.QRect(439, 169, 100, 591))
        self.frame_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.D_bound = QtGui.QFrame(self.frame_4)
        self.D_bound.setGeometry(QtCore.QRect(10, 100, 80, 16))
        self.D_bound.setFrameShadow(QtGui.QFrame.Raised)
        self.D_bound.setLineWidth(1)
        self.D_bound.setFrameShape(QtGui.QFrame.HLine)
        self.D_bound.setObjectName(_fromUtf8("D_bound"))
        self.splitter_2 = QtGui.QSplitter(self.base_frame1)
        self.splitter_2.setGeometry(QtCore.QRect(110, 770, 51, 41))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.lcd1 = QtGui.QLCDNumber(self.splitter_2)
        self.lcd1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd1.setAutoFillBackground(False)
        self.lcd1.setSmallDecimalPoint(False)
        self.lcd1.setNumDigits(2)
        self.lcd1.setDigitCount(2)
        self.lcd1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd1.setProperty("value", 3.0)
        self.lcd1.setProperty("intValue", 3)
        self.lcd1.setObjectName(_fromUtf8("lcd1"))
        self.label_13 = QtGui.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.splitter_4 = QtGui.QSplitter(self.base_frame1)
        self.splitter_4.setGeometry(QtCore.QRect(319, 759, 71, 61))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.layoutWidget_10 = QtGui.QWidget(self.splitter_4)
        self.layoutWidget_10.setObjectName(_fromUtf8("layoutWidget_10"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.lcd6 = QtGui.QLCDNumber(self.layoutWidget_10)
        self.lcd6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd6.setAutoFillBackground(False)
        self.lcd6.setSmallDecimalPoint(False)
        self.lcd6.setNumDigits(2)
        self.lcd6.setDigitCount(2)
        self.lcd6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd6.setProperty("value", 3.0)
        self.lcd6.setProperty("intValue", 3)
        self.lcd6.setObjectName(_fromUtf8("lcd6"))
        self.verticalLayout_14.addWidget(self.lcd6)
        self.lcd3 = QtGui.QLCDNumber(self.layoutWidget_10)
        self.lcd3.setEnabled(True)
        self.lcd3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd3.setAutoFillBackground(False)
        self.lcd3.setSmallDecimalPoint(False)
        self.lcd3.setNumDigits(2)
        self.lcd3.setDigitCount(2)
        self.lcd3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd3.setProperty("value", 3.0)
        self.lcd3.setProperty("intValue", 3)
        self.lcd3.setObjectName(_fromUtf8("lcd3"))
        self.verticalLayout_14.addWidget(self.lcd3)
        self.layoutWidget_11 = QtGui.QWidget(self.splitter_4)
        self.layoutWidget_11.setObjectName(_fromUtf8("layoutWidget_11"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_14 = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_15.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_15.addWidget(self.label_15)
        self.frame_2 = QtGui.QFrame(self.base_frame1)
        self.frame_2.setGeometry(QtCore.QRect(199, 139, 100, 591))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.B_bound = QtGui.QFrame(self.frame_2)
        self.B_bound.setEnabled(True)
        self.B_bound.setGeometry(QtCore.QRect(0, 380, 80, 16))
        self.B_bound.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.B_bound.setStyleSheet(_fromUtf8("QFrame[frameShape=\"4\"] /* QFrame::HLine == 0x0004 */\n"
                                             "                                        {\n"
                                             "                                        color: red;\n"
                                             "                                        }\n"
                                             "                                    "))
        self.B_bound.setFrameShadow(QtGui.QFrame.Raised)
        self.B_bound.setLineWidth(1)
        self.B_bound.setFrameShape(QtGui.QFrame.HLine)
        self.B_bound.setObjectName(_fromUtf8("B_bound"))
        self.splitter_5 = QtGui.QSplitter(self.base_frame1)
        self.splitter_5.setGeometry(QtCore.QRect(450, 760, 55, 54))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.layoutWidget_12 = QtGui.QWidget(self.splitter_5)
        self.layoutWidget_12.setObjectName(_fromUtf8("layoutWidget_12"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.lcd7 = QtGui.QLCDNumber(self.layoutWidget_12)
        self.lcd7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd7.setAutoFillBackground(False)
        self.lcd7.setSmallDecimalPoint(False)
        self.lcd7.setNumDigits(2)
        self.lcd7.setDigitCount(2)
        self.lcd7.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd7.setProperty("value", 3.0)
        self.lcd7.setProperty("intValue", 3)
        self.lcd7.setObjectName(_fromUtf8("lcd7"))
        self.verticalLayout_16.addWidget(self.lcd7)
        self.lcd4 = QtGui.QLCDNumber(self.layoutWidget_12)
        self.lcd4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd4.setAutoFillBackground(False)
        self.lcd4.setSmallDecimalPoint(False)
        self.lcd4.setNumDigits(2)
        self.lcd4.setDigitCount(2)
        self.lcd4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd4.setProperty("value", 3.0)
        self.lcd4.setProperty("intValue", 3)
        self.lcd4.setObjectName(_fromUtf8("lcd4"))
        self.verticalLayout_16.addWidget(self.lcd4)
        self.layoutWidget_13 = QtGui.QWidget(self.splitter_5)
        self.layoutWidget_13.setObjectName(_fromUtf8("layoutWidget_13"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_16 = QtGui.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_17.addWidget(self.label_16)
        self.label_17 = QtGui.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_17.addWidget(self.label_17)
        self.frame_3 = QtGui.QFrame(self.base_frame1)
        self.frame_3.setGeometry(QtCore.QRect(320, 130, 100, 601))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.C_bound = QtGui.QFrame(self.frame_3)
        self.C_bound.setGeometry(QtCore.QRect(10, 230, 74, 6))
        self.C_bound.setFrameShadow(QtGui.QFrame.Raised)
        self.C_bound.setLineWidth(1)
        self.C_bound.setFrameShape(QtGui.QFrame.HLine)
        self.C_bound.setObjectName(_fromUtf8("C_bound"))
        self.splitter_3 = QtGui.QSplitter(self.base_frame1)
        self.splitter_3.setGeometry(QtCore.QRect(199, 749, 81, 61))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget_14 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget_14.setObjectName(_fromUtf8("layoutWidget_14"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.layoutWidget_14)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.lcd5 = QtGui.QLCDNumber(self.layoutWidget_14)
        self.lcd5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd5.setAutoFillBackground(False)
        self.lcd5.setSmallDecimalPoint(False)
        self.lcd5.setNumDigits(2)
        self.lcd5.setDigitCount(2)
        self.lcd5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd5.setProperty("value", 3.0)
        self.lcd5.setProperty("intValue", 3)
        self.lcd5.setObjectName(_fromUtf8("lcd5"))
        self.verticalLayout_18.addWidget(self.lcd5)
        self.lcd2 = QtGui.QLCDNumber(self.layoutWidget_14)
        self.lcd2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcd2.setAutoFillBackground(False)
        self.lcd2.setSmallDecimalPoint(False)
        self.lcd2.setNumDigits(2)
        self.lcd2.setDigitCount(2)
        self.lcd2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd2.setProperty("value", 3.0)
        self.lcd2.setProperty("intValue", 3)
        self.lcd2.setObjectName(_fromUtf8("lcd2"))
        self.verticalLayout_18.addWidget(self.lcd2)
        self.layoutWidget_15 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget_15.setObjectName(_fromUtf8("layoutWidget_15"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_18 = QtGui.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_19.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.layoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_19.addWidget(self.label_19)
        self.frame_1 = QtGui.QFrame(self.base_frame1)
        self.frame_1.setGeometry(QtCore.QRect(99, 139, 100, 600))
        self.frame_1.setFrameShape(QtGui.QFrame.Box)
        self.frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_1.setLineWidth(1)
        self.frame_1.setMidLineWidth(0)
        self.frame_1.setObjectName(_fromUtf8("frame_1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout.addWidget(self.base_frame1)
        self.base_frame2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_frame2.sizePolicy().hasHeightForWidth())
        self.base_frame2.setSizePolicy(sizePolicy)
        self.base_frame2.setMinimumSize(QtCore.QSize(860, 750))
        self.base_frame2.setMaximumSize(QtCore.QSize(860, 750))
        self.base_frame2.setStyleSheet(_fromUtf8("background:#999999;\n"
                                                 "                            "))
        self.base_frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.base_frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.base_frame2.setObjectName(_fromUtf8("base_frame2"))
        self.layoutWidget = QtGui.QWidget(self.base_frame2)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 130, 171, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_6.addWidget(self.label_21)
        self.verticalLayout_20.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.src_floor_box = QtGui.QTextBrowser(self.layoutWidget)
        self.src_floor_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.src_floor_box.setFont(font)
        self.src_floor_box.setStyleSheet(_fromUtf8("color:#FFFFFF"))
        self.src_floor_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.src_floor_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.src_floor_box.setReadOnly(False)
        self.src_floor_box.setObjectName(_fromUtf8("src_floor_box"))
        self.horizontalLayout_8.addWidget(self.src_floor_box)
        self.des_floor_box = QtGui.QTextBrowser(self.layoutWidget)
        self.des_floor_box.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.des_floor_box.setFont(font)
        self.des_floor_box.setStyleSheet(_fromUtf8("color:#FFFFFF"))
        self.des_floor_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.des_floor_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.des_floor_box.setReadOnly(False)
        self.des_floor_box.setObjectName(_fromUtf8("des_floor_box"))
        self.horizontalLayout_8.addWidget(self.des_floor_box)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_20.addLayout(self.horizontalLayout_7)
        self.layoutWidget_16 = QtGui.QWidget(self.base_frame2)
        self.layoutWidget_16.setGeometry(QtCore.QRect(50, 210, 201, 321))
        self.layoutWidget_16.setObjectName(_fromUtf8("layoutWidget_16"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.src_slider = QtGui.QSlider(self.layoutWidget_16)
        self.src_slider.setMinimum(1)
        self.src_slider.setMaximum(60)
        self.src_slider.setPageStep(3)
        self.src_slider.setOrientation(QtCore.Qt.Vertical)
        self.src_slider.setObjectName(_fromUtf8("src_slider"))
        self.horizontalLayout_9.addWidget(self.src_slider)
        self.des_slider = QtGui.QSlider(self.layoutWidget_16)
        self.des_slider.setAutoFillBackground(False)
        self.des_slider.setMaximum(60)
        self.des_slider.setPageStep(3)
        self.des_slider.setSliderPosition(0)
        self.des_slider.setOrientation(QtCore.Qt.Vertical)
        self.des_slider.setInvertedAppearance(False)
        self.des_slider.setInvertedControls(False)
        self.des_slider.setTickPosition(QtGui.QSlider.NoTicks)
        self.des_slider.setTickInterval(0)
        self.des_slider.setObjectName(_fromUtf8("des_slider"))
        self.horizontalLayout_9.addWidget(self.des_slider)
        self.label_22 = QtGui.QLabel(self.base_frame2)
        self.label_22.setGeometry(QtCore.QRect(130, 20, 631, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("黑体"))
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.line = QtGui.QFrame(self.base_frame2)
        self.line.setGeometry(QtCore.QRect(80, 530, 151, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.confirm_button = QtGui.QPushButton(self.base_frame2)
        self.confirm_button.setEnabled(True)
        self.confirm_button.setGeometry(QtCore.QRect(100, 570, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirm_button.setFont(font)
        self.confirm_button.setStyleSheet(_fromUtf8("color:rgb(0, 0, 0);\n"
                                                    "                                    background-color:rgb(118, 118, 118)\n"
                                                    "                                "))
        self.confirm_button.setAutoDefault(False)
        self.confirm_button.setDefault(False)
        self.confirm_button.setFlat(False)
        self.confirm_button.setObjectName(_fromUtf8("confirm_button"))
        self.clear_button = QtGui.QPushButton(self.base_frame2)
        self.clear_button.setGeometry(QtCore.QRect(340, 570, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet(_fromUtf8("color:rgb(0, 0, 0);\n"
                                                  "                                    background-color:rgb(118, 118, 118)\n"
                                                  "                                "))
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.shuffle_button = QtGui.QPushButton(self.base_frame2)
        self.shuffle_button.setGeometry(QtCore.QRect(490, 570, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.shuffle_button.setFont(font)
        self.shuffle_button.setStyleSheet(_fromUtf8("color:rgb(0, 0, 0);\n"
                                                    "                                    background-color:rgb(118, 118, 118)\n"
                                                    "                                "))
        self.shuffle_button.setObjectName(_fromUtf8("shuffle_button"))
        self.layoutWidget1 = QtGui.QWidget(self.base_frame2)
        self.layoutWidget1.setGeometry(QtCore.QRect(260, 132, 509, 411))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(-1, -1, 2, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_24 = QtGui.QLabel(self.layoutWidget1)
        self.label_24.setMinimumSize(QtCore.QSize(200, 0))
        self.label_24.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout.addWidget(self.label_24)
        self.pass_info_broswer = QtGui.QTextBrowser(self.layoutWidget1)
        self.pass_info_broswer.setMinimumSize(QtCore.QSize(200, 0))
        self.pass_info_broswer.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pass_info_broswer.setFont(font)
        self.pass_info_broswer.setObjectName(_fromUtf8("pass_info_broswer"))
        self.verticalLayout.addWidget(self.pass_info_broswer)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.label_25 = QtGui.QLabel(self.layoutWidget1)
        self.label_25.setMinimumSize(QtCore.QSize(300, 0))
        self.label_25.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_22.addWidget(self.label_25)
        self.sch_info_broswer = QtGui.QTextBrowser(self.layoutWidget1)
        self.sch_info_broswer.setMinimumSize(QtCore.QSize(300, 0))
        self.sch_info_broswer.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sch_info_broswer.setFont(font)
        self.sch_info_broswer.setObjectName(_fromUtf8("sch_info_broswer"))
        self.verticalLayout_22.addWidget(self.sch_info_broswer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_23 = QtGui.QLabel(self.layoutWidget1)
        self.label_23.setMinimumSize(QtCore.QSize(500, 0))
        self.label_23.setMaximumSize(QtCore.QSize(500, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_4.addWidget(self.label_23)
        self.chg_info_broswer = QtGui.QTextBrowser(self.layoutWidget1)
        self.chg_info_broswer.setMinimumSize(QtCore.QSize(500, 0))
        self.chg_info_broswer.setMaximumSize(QtCore.QSize(500, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chg_info_broswer.setFont(font)
        self.chg_info_broswer.setObjectName(_fromUtf8("chg_info_broswer"))
        self.verticalLayout_4.addWidget(self.chg_info_broswer)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.reset_button = QtGui.QPushButton(self.base_frame2)
        self.reset_button.setGeometry(QtCore.QRect(630, 570, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reset_button.setFont(font)
        self.reset_button.setStyleSheet(_fromUtf8("color:rgb(0, 0, 0);\n"
                                                  "                                    background-color:rgb(118, 118, 118)\n"
                                                  "                                "))
        self.reset_button.setObjectName(_fromUtf8("reset_button"))
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget_16.raise_()
        self.label_22.raise_()
        self.line.raise_()
        self.confirm_button.raise_()
        self.clear_button.raise_()
        self.shuffle_button.raise_()
        self.reset_button.raise_()
        self.horizontalLayout.addWidget(self.base_frame2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Elevator", None))
        self.label_13.setText(_translate("MainWindow", "A", None))
        self.label_14.setText(_translate("MainWindow", "C2", None))
        self.label_15.setText(_translate("MainWindow", "C1", None))
        self.label_16.setText(_translate("MainWindow", "D2", None))
        self.label_17.setText(_translate("MainWindow", "D1", None))
        self.label_18.setText(_translate("MainWindow", "B2", None))
        self.label_19.setText(_translate("MainWindow", "B1", None))
        self.label_20.setText(_translate("MainWindow", "呼梯楼层", None))
        self.label_21.setText(_translate("MainWindow", "目的楼层", None))
        self.label_22.setText(_translate("MainWindow", "一井道七轿厢超级电梯调度模拟系统", None))
        self.confirm_button.setText(_translate("MainWindow", "确认", None))
        self.clear_button.setText(_translate("MainWindow", "重置", None))
        self.shuffle_button.setText(_translate("MainWindow", "随机", None))
        self.label_24.setText(_translate("MainWindow", "乘客信息", None))
        self.pass_info_broswer.setHtml(_translate("MainWindow",
                                                  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                                                  "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                </p>\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>",
                                                  None))
        self.label_25.setText(_translate("MainWindow", "调度信息", None))
        self.sch_info_broswer.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'SimSun\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                                </p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>",
                                                 None))
        self.label_23.setText(_translate("MainWindow", "换乘信息", None))
        self.chg_info_broswer.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                                                        </p>\n"
                                                 "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>",
                                                 None))
        self.reset_button.setText(_translate("MainWindow", "复位", None))


if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
